/**
 * SMS Gateway client — sends SMS through an Android phone running the
 * "SMS Gateway for Android" app (https://sms-gate.app).
 *
 * The phone holds the SIM (BVI business number 284-544-8088) and exposes
 * a small HTTP server on the shop's WiFi. We POST to it and the phone
 * sends the SMS over its cellular plan — no per-message cost.
 *
 * Required env vars:
 *   SMS_GATEWAY_URL       e.g. http://192.168.1.42:8080
 *   SMS_GATEWAY_USERNAME  generated by the app
 *   SMS_GATEWAY_PASSWORD  generated by the app
 *
 * If any of those are missing, sendSms() is a no-op (logs a warning).
 * There is intentionally NO Twilio fallback — the user is shutting Twilio
 * down to stop the bleed.
 */

import { logger } from "./logger";

export interface SendSmsResult {
  ok: boolean;
  id?: string;
  error?: string;
}

export async function sendSms(toE164: string, body: string): Promise<SendSmsResult> {
  const baseUrl  = process.env.SMS_GATEWAY_URL;
  const username = process.env.SMS_GATEWAY_USERNAME;
  const password = process.env.SMS_GATEWAY_PASSWORD;

  if (!baseUrl || !username || !password) {
    logger.warn("[sms] SMS_GATEWAY_URL/USERNAME/PASSWORD not set — skipping SMS send");
    return { ok: false, error: "gateway_not_configured" };
  }

  const credentials = Buffer.from(`${username}:${password}`).toString("base64");
  const url = `${baseUrl.replace(/\/+$/, "")}/messages`;

  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), 8000);

  try {
    const resp = await fetch(url, {
      method: "POST",
      headers: {
        "Authorization": `Basic ${credentials}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        message: body,
        phoneNumbers: [toE164],
      }),
      signal: controller.signal,
    });

    const text = await resp.text();
    if (!resp.ok) {
      logger.error({ status: resp.status, body: text.slice(0, 300) },
        "[sms] gateway send failed");
      return { ok: false, error: `http_${resp.status}` };
    }

    let id: string | undefined;
    try {
      const data = JSON.parse(text);
      id = data?.id;
    } catch {
      // gateway responded 2xx with non-JSON — still treat as success
    }
    logger.info({ to: toE164, id }, "[sms] sent via gateway");
    return { ok: true, id };
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : String(err);
    logger.error({ err: msg }, "[sms] gateway send error");
    return { ok: false, error: msg };
  } finally {
    clearTimeout(timeout);
  }
}

/** Lightweight health check — pings the gateway's /health endpoint. */
export async function pingSmsGateway(): Promise<boolean> {
  const baseUrl = process.env.SMS_GATEWAY_URL;
  if (!baseUrl) return false;
  try {
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), 3000);
    const resp = await fetch(`${baseUrl.replace(/\/+$/, "")}/health`, {
      signal: controller.signal,
    });
    clearTimeout(timeout);
    return resp.ok;
  } catch {
    return false;
  }
}
