// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/direction-a/Obsidian.tsx": () => import("../components/mockups/direction-a/Obsidian.tsx"),
  "./components/mockups/direction-c/IslandLuxe.tsx": () => import("../components/mockups/direction-c/IslandLuxe.tsx"),
  "./components/mockups/direction-b/CreamCopper.tsx": () => import("../components/mockups/direction-b/CreamCopper.tsx"),
  "./components/mockups/metallic/MetallicAdmin.tsx": () => import("../components/mockups/metallic/MetallicAdmin.tsx"),
  "./components/mockups/metallic/MetallicKDS.tsx": () => import("../components/mockups/metallic/MetallicKDS.tsx"),
  "./components/mockups/metallic/MetallicPOS.tsx": () => import("../components/mockups/metallic/MetallicPOS.tsx"),
  "./components/mockups/metallic/MetallicStore.tsx": () => import("../components/mockups/metallic/MetallicStore.tsx"),
  "./components/mockups/wa-receipt/WhatsAppReceipt.tsx": () => import("../components/mockups/wa-receipt/WhatsAppReceipt.tsx")
};
