// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/island-templates/BoldTropical.tsx": () => import("../components/mockups/island-templates/BoldTropical.tsx"),
  "./components/mockups/island-templates/CleanModern.tsx": () => import("../components/mockups/island-templates/CleanModern.tsx"),
  "./components/mockups/island-templates/DarkVibrant.tsx": () => import("../components/mockups/island-templates/DarkVibrant.tsx")
};
