// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/direction-a/Obsidian.tsx": () => import("../components/mockups/direction-a/Obsidian.tsx"),
  "./components/mockups/direction-b/CreamCopper.tsx": () => import("../components/mockups/direction-b/CreamCopper.tsx"),
  "./components/mockups/direction-c/IslandLuxe.tsx": () => import("../components/mockups/direction-c/IslandLuxe.tsx")
};
